### ISSUE TITLE
Bug on Readme.md

### ISSUE THREAD

**Issue by tracyhenry** [CommanderLee/SurfaceKeyboard#1]
Hey dude, 

```
  I think it's cooooooooooooool to change 'Zhen Li, Tsinghua University' to 'Zhen Li, UMD' or something. 
```

Best,
A totally obsessed fan of yours

**Comment by CommanderLee** [comment]
Oh no, the copyright belongs to Tsinghua because I am working  in my lab now.

**Comment by tracyhenry** [comment]
# I found that even opening a issue is counted as a contribution!
